name = "odepack"
author = "Nicholas Wogan"
maintainer = "Nicholas Wogan"
license = "Public Domain"
description = "Modern Fortran interface to part of ODEPACK"
homepage = "https://github.com/Nicholaswogan/odepack"
keywords = ["ODE"]

[fortran]
source-form = "default"
implicit-external = true
implicit-typing = true

[library]
source-dir = "src"

[build]
auto-executables = false
auto-tests = true